### PR TITLE
Show/hide custom frame range attributes based on Frame Range source value

### PR DESCRIPTION
**Pull request by BigRoy**
## Changelog Description

Show/hide custom frame range attributes based on Frame Range source value

## Additional info

Requires PR https://github.com/ynput/ayon-core/pull/935

## Testing notes:

1. Publisher UI instance attributes should toggle "custom frame range" attributes based on the Frame Range source set on the instance.

image

image

### CODE REVIEW

**Comment by BigRoy** [comment]
> BTW I really think this should be merged [ynput/ayon-core#889](https://github.com/ynput/ayon-core/pull/889) and here should be used `visible=False` instead of `hidden=True`.

Fine with me - let me know when merged. ;)

**Comment by BigRoy** [comment]
> BTW I really think this should be merged [ynput/ayon-core#889](https://github.com/ynput/ayon-core/pull/889) and here should be used `visible=False` instead of `hidden=True`.

Implemented. ✅

**Comment by LiborBatek** [comment]
not sure why but I cannot create Render saver in this branch just ```Image(saver)``` which isnt suitable for testing this PR.

@BigRoy is there any reasoning for that or just accident?

**Comment by BigRoy** [comment]
> not sure why but I cannot create Render saver in this branch just `Image(saver)` which isnt suitable for testing this PR.
> 
> @BigRoy is there any reasoning for that or just accident?

Likely due to code errors occurring - did you correctly pull the update of the 'required' core branch linked in the PR?

**Review by LiborBatek — APPROVED** [review]
Now it works like charm! LGTM

Fusion_context_fr

**Comment by iLLiCiTiT** [comment]
NOTE: This PR should have `bump minor` label and should bump required version of ayon-core, or is it backwards compatible?

**Comment by BigRoy** [comment]
> NOTE: This PR should have `bump minor` label and should bump required version of ayon-core, or is it backwards compatible?

Added the label - and awaiting the rest until the required PR is merged, etc.

**Review by jakubjezek001 — DISMISSED** [review]
We need to change ayon-core dependency version to follow the required changes from https://github.com/ynput/ayon-core/pull/935. @BigRoy could you please also adjust the `package.py` within this PR?

**Comment by BigRoy** [comment]
Thanks @jakubjezek001 - it's similar to my question [here](https://github.com/ynput/ayon-maya/pull/138#issuecomment-2427768142) - but does it make sense to bump that dependency now if `ayon-core` is not released yet?

**Pull request merged**
